### ISSUE TITLE
AVR(Arduino, ESP32) compatible

### ISSUE THREAD

**Issue by garudaonekh** [vacabun/PAN3031_demo#3]
Hi,
Do you have any PAN3031 library for Arduino family?
I bought a few chip and plan to get it working on Attiny85 and ESp32 but can't find any library

**Comment by vacabun** [comment]
You can modify the file _pan3031_port.c_ to port the library from STM32 to Arduino family. 
In this file define the spi interface used by PAN3031.

**Comment by garudaonekh** [comment]
Thanks. But this is beyond my programming skill.
